title: ThatOSDeveloper's basement
description: >-
  A personal blog for hobby OS developers exploring low-level programming and custom kernels. Also a demo showcase website for my cool hobbys!

baseurl: ""
url: "https://thatosdeveloper.us/"
email: 
codeberg: https://codeberg.org/ThatOSDeveloper

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
