title: ThatOSDeveloper's blog
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog for hobby OS developers exploring low-level programming and custom kernels.

baseurl: ""
url: "https://thatosdeveloper.us/"
email: thatosdeveloper@thatosdeveloper.us
codeberg: https://codeberg.org/ThatOSDeveloper

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
